version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: events
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
#
#  event-service:
#    build:
#      context: .
#      dockerfile: event-service/Dockerfile
#    ports:
#      - "50051:50051"
#      - "8081:8081"
#    environment:
#      - GRPC_PORT=50051
#      - HTTP_PORT=8081
#      - DATABASE_URL=root:password@tcp(mysql:3306)/events?parseTime=true
#    depends_on:
#      mysql:
#        condition: service_healthy
#
#  ticket-service:
#    build:
#      context: .
#      dockerfile: ticket-service/Dockerfile
#    ports:
#      - "50052:50052"
#      - "8082:8082"
#    environment:
#      - GRPC_PORT=50052
#      - HTTP_PORT=8082
#      - MONGO_URI=mongodb://root:password@mongodb:27017
#      - EVENT_SERVICE_ADDR=event-service:50051
#    depends_on:
#      mongodb:
#        condition: service_healthy
#      event-service:
#        condition: service_started
#
#  notification-service:
#    build:
#      context: .
#      dockerfile: notification-service/Dockerfile
#    ports:
#      - "50053:50053"
#      - "8083:8083"
#    environment:
#      - GRPC_PORT=50053
#      - HTTP_PORT=8083
#      - DATABASE_URL=root:password@tcp(mysql:3306)/notifications?parseTime=true
#      - TICKET_SERVICE_ADDR=ticket-service:50052
#    depends_on:
#      mysql:
#        condition: service_healthy
#      ticket-service:
#        condition: service_started

volumes:
  mysql-data:
  mongo-data: